create table if not exists book_engagement (id integer primary key, likes bigint not null default 0);
insert into book_engagement(id,likes) values (1,0) on conflict (id) do nothing;
create table if not exists comments (id bigint generated by default as identity primary key, book_id text not null, name text not null check(char_length(name) between 1 and 60), message text not null check(char_length(message) between 1 and 500), approved boolean not null default true, created_at timestamptz not null default now());
alter table book_engagement enable row level security;
alter table comments enable row level security;
create or replace function increment_book_like(p_book_id integer) returns bigint language sql security definer set search_path=public as $$ update book_engagement set likes=likes+1 where id=p_book_id returning likes; $$;
grant execute on function increment_book_like(integer) to service_role;
