-- Khamoshi ki Awaaz engagement schema
create table if not exists public.book_engagement (id bigint primary key, likes bigint not null default 0);
insert into public.book_engagement(id,likes) values (1,0) on conflict (id) do nothing;
create table if not exists public.comments (id bigint generated by default as identity primary key, book_id text not null, name text not null, message text not null, approved boolean not null default true, created_at timestamptz not null default now());
create or replace function public.increment_book_like(p_book_id bigint) returns bigint language plpgsql as $$ declare new_likes bigint; begin update public.book_engagement set likes=likes+1 where id=p_book_id returning likes into new_likes; return coalesce(new_likes,0); end; $$;